todo_web/todo_app/urls.py
from django.urls import path 
from . import views

app_name = 'todo_app'

urlpatterns = [
    path('todo_list', views.TodoPage.as_view(), name='todolist'),
    path('create-tasks', views.TodoCreate.as_view(), name='create-tasks'),
    path('item/<int:pk>/', views.TodoDetail.as_view(), name='item'),
    path('edit/<int:pk>/view', views.TodoUpdate.as_view(), name='edit'),
]

todo_web/todo_auth/urls.py
from django.urls import path
from . import views

app_name = 'todo-auth'

urlpatterns = [
    path('login', views.loginpage, name='login'),
    path('signup', views.signup_page, name='signup'),
    path('logout', views.logoutpage, name='logout'),
]

todo_web/todo_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    path('auth/', include(('todo_auth.urls'), namespace='todo_auth'))
]

todo_web/todo_app/models.py
from django.db import models


class TodoList(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title
# Create your models here.

todo_web/todo_auth/models.py
from django.db import models

# Create your models here.

todo_web/todo_app/forms.py
from django import forms
from .models import TodoList


class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = '__all__'
    

todo_web/todo_auth/forms.py
from django import forms
from django.contrib.auth.models import User
from  django.contrib.auth.forms import UserCreationForm

class TaskCreator(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User 
        fields = ['username', 'email', 'password1', 'password2']

todo_web/todo_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import TodoList
from .forms import TodoForm



class TodoCreate(CreateView):
    model = TodoList
    form_class = TodoForm
    template_name = 'todo_app/todo-create.html'
    success_url = 'todo_list'

class TodoPage(ListView):
    model = TodoList
    template_name = 'todo_app/todolist_list.html'
    context_object_name = 'tasks'

class TodoDetail(DetailView):
    model = TodoList
    template_name = 'todo_app/todo-detail.html'
    context_object_name = 'tasks'


class TodoUpdate(UpdateView):
    model = TodoList
    context_object_name = 'tasks' 
    template_name = 'todo_app/todo-update.html'
    form_class = TodoForm
    success_url = reverse_lazy('todo_list')

todo_web/todo_auth/views.py
from django.shortcuts import render, redirect
from .forms import TaskCreator
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password




def signup_page(request):
    
    if request.method == 'POST':
        form = TaskCreator(request.POST)#to grab input data
        
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"hi {username} your account creation was a success")
            new_user = TaskCreator(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect('todo_app:todo_list')
        
    else:
        print('user not registered')
        form = TaskCreator()


    context = {
        'form':form,

    }
    return render (request, 'todo_app/auth/sign-up.html', context)

def loginpage(request):
    if request.method=='POST':
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('todo_app:todo_list')
        else:
            error_message = 'Invalid Username and Password'
            return render(request, 'todo_app/auth/login.html', {'error_message':error_message})

    return render(request, 'todo_app/auth/login.html')


def logoutpage(request):
    logout(request)
    messages.success(request, 'you have successfully logged out')
    return redirect('todo_auth:login')
# Create your views here.

todo_web/templates/todo_app/partials/base.html
{% load static%}

<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>
<body class="">
    {% if user.is_authenticated%}
    <nav class="h-12 bg-gray-800 mb-7 p-2 flex items-stretch justify-between">
        <a href="{% url 'todo-auth:logout'%}" class="text-gray-300">logout</a>
        
    </nav>
    {% else %}
    <nav class="h-12 bg-gray-800 mb-7 p-2 flex items-stretch justify-between">
        <div class="gap-3">
            <a href="{% url 'todo-auth:login'%}" class="text-gray-300">login</a>
            <a href="{% url 'todo-auth:signup'%}" class="text-gray-300">sign-up</a>
        </div>
        
    </nav>
    <p class="shadow-md text-red-500 p-2 mb-3">you are not logged in!</p>

    {% endif %}
    {% block content%}

    {% endblock %}
</body>
</html

todo_web/templates/todo_app/todo-create.html
{% extends 'todo_app/partials/base.html'%}
{% load static %}

{% block content %}
    <div class="p-4">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="h-12 w-24 font-bold bg-blue-500 text-white rounded">submit</button>
        </form>
    </div>
    
{% endblock %}

todo_web/templates/todo_app/todo-detail.html
{% extends 'todo_app/partials/base.html'%}

{% block content %}
<div class="flex flex-col place-items-center">
    <div class="mb-12 ">
        <h1 class="font-bold">{{tasks.title}}</h1>
        <p>{{tasks.description|truncatechars:50 }}</p>
        <p class="text-sm">{{tasks.date}}</p>
    </div>
    <a href="{% url 'todo_app:edit' tasks.pk %} " class="p-2 w-32 text-white bg-blue-500 rounded">Edit</a>
</div>

 
{%  endblock %}

todo_web/templates/todo_app/todo-update.html
{{form.as_p}}
<button type="submit">Update</button>

todo_web/templates/todo_app/todolist_list.html
{% extends 'todo_app/partials/base.html'%}
{% block content%}
  <div class="grid place-items-center">
    <div class="pb-2 border-gray-200 h-full w-96 shadow-md border border-blue-500 rounded" style="width: 50vw; min-width: 30vw;">
        <div class="h-24 w-full shadow-md mb-4 p-2">
            <h1 class="font-bold border-b border-grey-500">{{user.username}}</h1>
            <p class="text-gray-400 text-xs">you have complete tasks</p>
        </div>

        {% for task in tasks%}
        <div class="p-2">
            <div class="w-full h-12 shadow-md rounded border-gray-200 flex items-stretch justify-between gap-1 w-4/5 border border-blue-500">
                <a href="{%url 'todo_app:item' task.pk%}" class="p-3">{{task.title}}</a>
                <div class="flex items-stretch ">
                    <div class="h-full w-12 bg-blue-500 rounded cursor-pointer " >
                        <div class="">
                            <a href="" class="text-white font-bold grid place-items-center pt-2">DEL</a>
                        </div>
                    </div>
                    <div class="h-full w-12 bg-yellow-500 rounded cursor-pointer" >
                       
                        <a href="" class="font-bold text-white grid place-items-center pt-2 " >EDIT</a>
                        
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
        
      </div>
  </div>
{% endblock %}